# Generated by Django 4.2.11 on 2024-03-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitgetapi',
            old_name='user_id',
            new_name='user',
        ),
    ]
