# Generated by Django 4.2.11 on 2024-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_bitgetapi_user_bybitapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_site_name', models.CharField(max_length=200)),
                ('endpoint_name', models.CharField(max_length=200)),
                ('endpoint_url', models.CharField(max_length=200)),
                ('auth_required', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=200)),
            ],
        ),
    ]
