# Generated by Django 4.2.11 on 2024-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_apiendpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoints',
            name='auth_required',
            field=models.BooleanField(),
        ),
    ]
