# Generated by Django 4.2.11 on 2024-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_apiendpoints_auth_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoints',
            name='endpoint_params',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
