# Generated by Django 4.2.11 on 2024-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_okxapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okxapi',
            name='access_passphrase',
            field=models.CharField(max_length=200),
        ),
    ]
