# Generated by Django 4.2.11 on 2024-03-24 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_alter_apiendpoints_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoMarketAPICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('access_passphrase', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bybitapi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='okxapi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='apiendpoints',
            name='api_site_name',
        ),
        migrations.DeleteModel(
            name='BitGetAPI',
        ),
        migrations.DeleteModel(
            name='BybitAPI',
        ),
        migrations.DeleteModel(
            name='OkxAPI',
        ),
        migrations.AddField(
            model_name='cryptomarketapicredentials',
            name='crypto_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.cryptomarkets'),
        ),
        migrations.AddField(
            model_name='cryptomarketapicredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiendpoints',
            name='crypto_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.cryptomarkets'),
        ),
    ]
