# Generated by Django 4.2.11 on 2024-03-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_cryptomarketapicredentials_cryptomarkets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoints',
            name='crypto_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cryptomarkets'),
        ),
        migrations.AlterField(
            model_name='cryptomarketapicredentials',
            name='crypto_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cryptomarkets'),
        ),
    ]
