# Generated by Django 4.2.11 on 2024-03-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_apiendpoints_is_active_cryptomarkets_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiendpoints',
            options={'verbose_name': 'API Endpoint', 'verbose_name_plural': 'API Endpoints'},
        ),
        migrations.AlterModelOptions(
            name='cryptomarketapicredentials',
            options={'verbose_name': 'Crypto Market API Credantial', 'verbose_name_plural': 'Crypto Market API Credantials'},
        ),
        migrations.AlterModelOptions(
            name='cryptomarkets',
            options={'verbose_name': 'Crypto Market', 'verbose_name_plural': 'Crypto Markets'},
        ),
    ]
