# Generated by Django 4.2.11 on 2024-04-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_futurestrading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuturesTrading',
        ),
    ]
