# Generated by Django 4.2.11 on 2024-04-17 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0020_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='membership',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
    ]
